Add Pyannote VAD pipelines
UrbanResiliencyInitiative/lang-of-pol pull request #46
Opened 2023-01-13 17:45 UTC by ShiyangLai

Pyannote VAD pipeline

2023-01-13 22:16 UTC, graziul commented on pipelines/vad/utils.py
> +def generate_ramdom_code():
"generate_ramdom_code" meant to be "generate_random_code"? Unsure if this breaks anything anywhere but assumed a typo.

2023-01-14 06:35 UTC, merged

2023-01-14 18:08 UTC, graziul requested changes
Please remove transcripts from one notebook - looks great otherwise!

2023-01-14 18:13 UTC, ShiyangLai commented on pipelines/vad/utils.py
> +def generate_ramdom_code():
This function is to generate an identical reference id for each assigned model training job which is different from the job id that is automatically assigned by computing clusters. The ids can be used to gain the logged training hyperparameters and the evaluation results of corresponding model training jobs. Sorry for the confusing name of the function, I will update it.

2023-01-14 18:14 UTC, graziul commented on pipelines/vad/utils.py
> +def generate_ramdom_code():
Okay, understood and thank you for explaining.

2023-01-14 18:15 UTC, ShiyangLai commented on pipelines/notebooks/bpc_vad_error.ipynb
> +       "      <td>HI UH LOOKS LIKE THE CALL IS IN APARTMENT THRE...</td>\n",
I will remove it now.